const participantes = [
  { numero: 1, nome: "FRANCISCO FERNANDES" },
  { numero: 2, nome: "FRANCISCO FERNANDES" },
  { numero: 3, nome: "FRANCISCO FERNANDES" },
  { numero: 4, nome: "FRANCISCO FERNANDES" },
  { numero: 5, nome: "FRANCISCO FERNANDES" },
  { numero: 6, nome: "FRANCISCO FERNANDES" },
  { numero: 7, nome: "FRANCISCO FERNANDES" },
  { numero: 8, nome: "FRANCISCO FERNANDES" },
  { numero: 9, nome: "FRANCISCO FERNANDES" },
  { numero: 10, nome: "FRANCISCO FERNANDES" },
  { numero: 11, nome: "FRANCISCO FERNANDES" },
  { numero: 12, nome: "FRANCISCO FERNANDES" },
  { numero: 13, nome: "FRANCISCO FERNANDES" },
  { numero: 14, nome: "FRANCISCO FERNANDES" },
  { numero: 15, nome: "FRANCISCO FERNANDES" },
  { numero: 16, nome: "FRANCISCO FERNANDES" },
  { numero: 17, nome: "ERLANE" },
  { numero: 18, nome: "ERLANE" },
  { numero: 19, nome: "ERLANE" },
  { numero: 20, nome: "ERLANE" },
  { numero: 21, nome: "ERLANE" },
  { numero: 22, nome: "NEILA" },
  { numero: 23, nome: "NEILA" },
  { numero: 24, nome: "NEILA" },
  { numero: 25, nome: "NEILA" },
  { numero: 26, nome: "NEILA" },
  { numero: 27, nome: "ADRIANA" },
  { numero: 28, nome: "RAMYS" },
  { numero: 29, nome: "CÉSAR" },
  { numero: 30, nome: "ALEX" },
  { numero: 31, nome: "MÁRCIO" },
  { numero: 32, nome: "MÁRCIO" },
  { numero: 33, nome: "MÁRCIO" },
  { numero: 34, nome: "MÁRCIO" },
  { numero: 35, nome: "RAMYS" },
  { numero: 36, nome: "MÁRCIO" },
  { numero: 37, nome: "MÁRCIO" },
  { numero: 38, nome: "MÁRCIO" },
  { numero: 39, nome: "MÁRCIO" },
  { numero: 40, nome: "MÁRCIO" },
  { numero: 41, nome: "MÁRCIO" },
  { numero: 42, nome: "CICI CAKES" },
  { numero: 43, nome: "ALEX" },
  { numero: 44, nome: "RAMYS" },
  { numero: 45, nome: "EDICARLA" },
  { numero: 46, nome: "IURY" },
  { numero: 47, nome: "IURY" },
  { numero: 48, nome: "ADRIANA" },
  { numero: 49, nome: "RAMYS" },
  { numero: 50, nome: "RAMYS" },
  { numero: 51, nome: "JEVÂNIA" },
  { numero: 52, nome: "LELECA" },
  { numero: 53, nome: "JEVÂNIA" },
  { numero: 54, nome: "CICI CAKES" },
  { numero: 55, nome: "EDICARLA" },
  { numero: 56, nome: "CÉSAR" },
  { numero: 57, nome: "MAURÍLIO" },
  { numero: 58, nome: "LELECA" },
  { numero: 59, nome: "TIA CÉLIA" },
  { numero: 60, nome: "ROCILDA" },
  { numero: 61, nome: "JEVÂNIA" },
  { numero: 62, nome: "JEVÂNIA" },
  { numero: 63, nome: "JEVÂNIA" },
  { numero: 64, nome: "LELECA" },
  { numero: 65, nome: "ROCILDA" },
  { numero: 66, nome: "GISELE" },
  { numero: 67, nome: "GISELE" },
  { numero: 68, nome: "GISELE" },
  { numero: 69, nome: "GISELE" },
  { numero: 70, nome: "GISELE" },
  { numero: 71, nome: "ERLANE" },
  { numero: 72, nome: "MAURÍLIO" },
  { numero: 73, nome: "ERLANE" },
  { numero: 74, nome: "ROCILDA" },
  { numero: 75, nome: "EDICARLA" },
  { numero: 76, nome: "LELECA" },
  { numero: 77, nome: "GRACIETE" },
  { numero: 78, nome: "CICI CAKES" },
  { numero: 79, nome: "GRACIETE" },
  { numero: 80, nome: "GRACIETE" },
  { numero: 81, nome: "TIA CÉLIA" },
  { numero: 82, nome: "TIA CÉLIA" },
  { numero: 83, nome: "TIA CÉLIA" },
  { numero: 84, nome: "TIA CÉLIA" },
  { numero: 85, nome: "CICI CAKES" },
  { numero: 86, nome: "MÁRCIO JOSÉ" },
  { numero: 87, nome: "ROCILDA" },
  { numero: 88, nome: "LELECA" },
  { numero: 89, nome: "GRACIETE" },
  { numero: 90, nome: "GRACIETE" },
  { numero: 91, nome: "ERLANE" },
  { numero: 92, nome: "MANU" },
  { numero: 93, nome: "ERLANE" },
  { numero: 94, nome: "MAURÍLIO" },
  { numero: 95, nome: "CICI CAKES" },
  { numero: 96, nome: "TIA DUDU" },
  { numero: 97, nome: "MANU" },
  { numero: 98, nome: "TIA DUDU" },
  { numero: 99, nome: "TIA DUDU" },
  { numero: 100, nome: "ROCILDA" }
];
